# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-17 01:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SiteSetting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('response_limit', models.PositiveSmallIntegerField(default=80)),
                ('manipulation_check_threshold', models.PositiveSmallIntegerField(choices=[(0, 0), (20, 20), (40, 40), (60, 60), (80, 80), (100, 100)], default=60)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
