# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-13 04:08
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EyewitnessStimuli',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.IntegerField(choices=[(60, 60), (80, 80), (100, 100)])),
                ('lineup_race', models.CharField(choices=[('B', 'black'), ('W', 'white')], max_length=1)),
                ('lineup_number', models.CharField(choices=[('B1', 'B1'), ('B2', 'B2'), ('B3', 'B3'), ('B4', 'B4'), ('B5', 'B5'), ('B6', 'B6'), ('W1', 'W1'), ('W2', 'W2'), ('W3', 'W3'), ('W4', 'W4'), ('W5', 'W5'), ('W6', 'W6')], max_length=2)),
                ('category', models.CharField(choices=[('O1', 'O1'), ('Omany', 'Omany'), ('R', 'R'), ('U1', 'U1'), ('F', 'F')], max_length=10)),
                ('statement', models.TextField(max_length=100)),
                ('statementOnly', models.TextField(max_length=100)),
                ('chosen_face', models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6)])),
                ('lineup_order', models.CharField(max_length=14)),
            ],
        ),
        migrations.CreateModel(
            name='Response',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.IntegerField(choices=[(0, 0), (20, 20), (40, 40), (60, 60), (80, 80), (100, 100)], null=True)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lineup_test_2.EyewitnessStimuli')),
            ],
        ),
        migrations.CreateModel(
            name='SecretCode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=14)),
                ('valid', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('userId', models.CharField(max_length=14, primary_key=True, serialize=False)),
                ('category', models.CharField(choices=[('O1', 'O1'), ('Omany', 'Omany'), ('R', 'R'), ('U1', 'U1'), ('F', 'F')], max_length=10)),
                ('StatementType', models.BooleanField()),
                ('example_response', models.IntegerField(choices=[(0, 0), (20, 20), (40, 40), (60, 60), (80, 80), (100, 100)], null=True)),
                ('sex', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=1, null=True)),
                ('birth_year', models.IntegerField(null=True)),
                ('race', models.CharField(max_length=10, null=True)),
                ('device', models.CharField(max_length=10, null=True)),
                ('comments', models.CharField(max_length=100, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='response',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lineup_test_2.User'),
        ),
    ]
