# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-08 20:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lineup_test_2', '0002_auto_20170508_0133'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='response',
            name='category',
        ),
        migrations.AddField(
            model_name='users',
            name='category',
            field=models.CharField(choices=[('O1', 'O1'), ('Omany', 'Omany'), ('R', 'R'), ('U1', 'U1'), ('F', 'F')], default='O1', max_length=10),
            preserve_default=False,
        ),
    ]
