# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-08 20:11
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lineup_test_2', '0003_auto_20170508_1603'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Users',
            new_name='User',
        ),
    ]
