# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-09 19:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lineup_test_2', '0004_auto_20170508_1611'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eyewitnessstimuli',
            name='category',
            field=models.CharField(choices=[('O1', 'O1'), ('Omany', 'Omany'), ('R', 'R'), ('U1', 'U1'), ('F', 'F'), ('Ex', 'Example')], max_length=10),
        ),
    ]
