# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-09 19:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lineup_test_2', '0005_auto_20170509_1518'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='example_response',
            field=models.IntegerField(choices=[(0, 0), (20, 20), (40, 40), (60, 60), (80, 80), (100, 100)], null=True),
        ),
        migrations.AlterField(
            model_name='eyewitnessstimuli',
            name='category',
            field=models.CharField(choices=[('O1', 'O1'), ('Omany', 'Omany'), ('R', 'R'), ('U1', 'U1'), ('F', 'F')], max_length=10),
        ),
    ]
