# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-11 17:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lineup_test_2', '0006_auto_20170509_1556'),
    ]

    operations = [
        migrations.CreateModel(
            name='SecretCode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=14)),
                ('valid', models.BooleanField(default=False)),
            ],
        ),
    ]
